export const enum AuthState {
  AUTHENTICATED,
  UNAUTHENTICATED,
  SESSION_EXPIRED,
  LOGGED_OUT,
}

export const enum ShowNavOptionOn {
  USER_AUTHENTICATED,
  USER_UNAUTHENTICATED,
  USER_ADMIN,
  ALL,
  TEST,
}
