export const enum AuthState {
	AUTHENTICATED = "AUTHENTICATED",
	UNAUTHENTICATED = "UNAUTHENTICATED",
	SESSION_EXPIRED = "SESSION_EXPIRED",
	LOGGED_OUT = "LOGGED_OUT",
}

export const enum ShowNavOptionOn {
	USER_AUTHENTICATED = "USER_AUTHENTICATED",
	USER_UNAUTHENTICATED = "USER_UNAUTHENTICATED",
	USER_ADMIN = "USER_ADMIN",
	ALL = "ALL",
	TEST = "TEST",
}

export enum NavOption {
	LOGIN,
	SIGNUP,
	LOGOUT,
	CLOUD,
}

export enum CloudMenuAction {
	UPLOAD,
	CREATE,
	DELETE,
	SORT,
}
